language: node_js

env:
  global:
    - AWS_DEFAULT_REGION=ap-southeast-2
    - DATA_BUCKET=send-that-invoice-data
    - MAIL_NAME='Josephine James'
    - MAIL_USER=davidj28827@gmail.com
    - MAIL_REPLY_TO=davidj28827@gmail.com
    - MAIL_HOST=smtp.gmail.com
    - MAIL_PORT=587

before_install:
  - npm install -g aws-cdk
install:
  - npm install
  - npm run pre-build
script:
  - cdk synth
deploy:
  - provider: script
    script:
      - cdk deploy --require-approval never
    skip_cleanup: true
    on:
      branch: master
