language: node_js
node_js:
- lts/*
addons:
  ssh_known_hosts:
  - 159.65.1.141
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/opt/send-that-invoice
  - REMOTE_USER=root
  - REMOTE_HOST=159.65.1.141
before_install:
- openssl aes-256-cbc -K $encrypted_f4f78a97320d_key -iv $encrypted_f4f78a97320d_iv -in deploy.enc -out deploy -d
install:
- true
before_script:
- chmod 600 deploy
- mv deploy ~/.ssh/id_rsa
deploy:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; fi'
- chmod +x "./scripts/deploy.sh"
- "./scripts/deploy.sh"
