language: node_js
node_js:
- 9.5.0
sudo: required
addons:
  ssh_known_hosts:
  - 159.65.1.141
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/opt/send-that-invoice
  - REMOTE_USER=root
  - REMOTE_HOST=159.65.1.141
install:
- true
before_script:
- chmod 600 deploy
- mv deploy ~/.ssh/id_rsa
script:
- chmod +x "./scripts/deploy.sh"
- "./scripts/deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_3024f06f859b_key -iv $encrypted_3024f06f859b_iv
  -in deploy.enc -out deploy -d
