language: node_js
node_js:
  - '10'
env:
  global:
    - secure: p3y8Qy0WftjANT+dq4bLGdKtCnIv8k7iVYY8DoUyMZf2IhejFy7TDi2BNKJulu5FgZ583KKpiptiqIJUal9t5WEokPvKfDCJBIWQTw1TCtamWI0EUplqnWCPfynwdKyVK4faCRJ7v0myznKxDlnPaNI03gPNBscLhOs8UhLfj8WV1cbo5vhsyqS722tA7VGA9Aj9KT3eh5nlreb3BqYscugj3X0Zfj2iEFfty5UEdsMXqCon3UHJY1/VmZacvi7d+XKVMJ7c5ALN1iOeobTDFRU0h1gBsBesXhEgtM8mUWRf8D1awj2iOxLTjBBmcS6S6Ygz3QqTv0tCQgvTI4zZ8Fh+AIAxydLHVmB1U9qbIQ05EbgyiXXqs0dt6WbAovROJqc+umoS/Vg8YySt7zoYR0EsY0REL5NsUUcvs8Bz5dnemi+p1MDb6jPjNxk0f3bbj7I7QPBOmEkWq6UrMZorHXWu7nUyY5nWWMQeeJl7ojBkPP43mwkGRG+2So4MFXWNxTJyE+//PgnWkhuSdCUJfM03B4w05gs9VSa9RTwM1cnPp0ji79gTPJBs3DSNXeje+1nLxpzTELDzh4PizUiBTvC9Rg1OafnDmv9jUXfnixU992mtnclgk8e4bWP82LXYT5GBVm7f1Hej+Ig47eWRpHe/hc0eWBIJ3dhGJ6BSsvs=
    - DATA_BUCKET=send-that-invoice-data
    - MAIL_NAME='Josephine James'
    - MAIL_USER=davidj28827@gmail.com
    - MAIL_REPLY_TO=davidj28827@gmail.com
    - MAIL_HOST=smtp.gmail.com
    - MAIL_PORT=587
before_install:
  - npm install -g aws-cdk
install:
  - npm install
  - npm run pre-build
script:
  - cdk synth
deploy:
  matrix:
    - provider: script
      script:
        - cdk deploy --require-approval never
      skip_cleanup: true
      on:
        branch: master
  secret_access_key:
    secure: jTyHAFf/yFZt796v1cw5rtmVjrHbiykvUOwB6aBF1rQkLnY0MroYn08jZMf9qBzRr+LGD9zpjr9kD9a/n5iLrdujGYWJCvXQl2mnIlWLlmCamOb9mKvYjnRaeNAd2OM3AvAFZUei9oidhjhVPCfl8+CGoGaFwc+MtVHPpuiRsaJpck21K/phSj8fiX6liMzZ/GHnCKrnHIS9+bP/UKWdbGwNRKyDGg2drBs74QKQMp9ecLgBB1eJutw4AH9ZOABRXjyeJgQAwM6YLZfqVhfhHBkJiGx/NZis8FIVgRomgs29zw4ofyPHgSzcqQVhvUarkAQyoiPvVHuVn7ze+O+4zbsqlwZ9xPigY5zDbJiyXFP0kCWx7elbG/SCcHwbVA/Elry9+g+Yfk+iOsNoaFchiU/wwHSbT7o5MaO9pa6qShe6QWIb540y6wESERZ19EkbebNxzrVj2lQn27wzDxwH30RLG9gZbWZOQdhmfn6p8wTc4Kc5QkziGpQWs0Nc/usSfgMe8D9v1EPigjj5t8b7AIoObOzgGbJuj+NYS03d+ERX1Yxstsao+H+r1/xHpeRg1Xk9mgq452klLcwfNvktM78AF7NqxouSzezOS4Q7s1SttQyKJgMa5rHj/6yU8p/N6BRDS1mGKjzT6nJdF5ZDVzwyCI8rae9Ye2l48jUc3QY=
  access_key_id:
    secure: FGns0td2bSyuQq/4Tuu2OPrjFQcnfjn9g0z3FmeMLA8cb3JBy3OcNg/HIkvnCMv/suwmSN2+wBwSzUEEyVSM34VI7PxVMdmmfIEdesfynoRVuTKOOnukg5MFTmnAMT/cwzeLPnr/u1h/TNXrnOt9CbyMJQmBxumLR/BJ5zpi0CF9NP2muWeV7pgF8yUKdYU6qzCdOOaJrsQSmdNW2XQ7jfpBfDqmuHPn8hUrv8rCGNGj09+V0IsJhxfbe/OkuDCpduiLlIAArM5k1KaUplLz9+/jzntgz/WJ6K20MbQlsJmih+kot92dYkkQLA3u+p0sHQXy1KtWdrvxmTdIy8XYDWbPKRB13qT/4Q6HUevpobEZC9APmteb+Ry/oJeYIEQmDSWwulGyPAJ2ZezVRAGOcz9mjj4bx5SctmB1t2g8U8E8sfVpUGUSUZOBYQS2iO3mdoHoHW/PWx2Fze87VADIZpEr/GC/19a2ywZEHUswFU07tKp0hFjwltoitKnpejjvos2wcQlbohi+v2VIdwa8lXurZTVkQJX/hZMwMOPtFZ4KBbS83d8wQtu5B/7WM4kvUGa3a5cHfD/wyFj4qFGTP4KJgXQpauD9F5SZL54T/nvfDFvkSgF2AI5AaJap7zWdtgOHwtlbDAd5APesWBrRrF749/n2iNIEB3yBCfelHdY=
